### ISSUE TITLE
BioPathNet on synthetic lethality (SL)

### ISSUE THREAD

**Issue by ZhengtingHuang888** [emyyue/BioPathNet#2]
Hi,

Thanks for your work on BioPathNet! I'm trying to run it on synthetic lethality (SL) data but couldn't find specific instructions. Could you provide some guidance or point me to relevant examples?

Appreciate any help!

Best wishes!

**Comment by emyyue** [comment]
Hi,

thanks for your question! The [SynLethDB](https://synlethdb.sist.shanghaitech.edu.cn/) data we used is from the repository of [KR4SL](https://github.com/JieZheng-ShanghaiTech/KR4SL/tree/main/data/transductive). We further processed the data (e.g. by removing reverse relations ('duplicated' triplets), as they are introduced natively in BioPathNet) using the script in [reproduce/synleth/02_prepare_data.py](https://github.com/emyyue/BioPathNet/tree/main/reproduce/synleth).

Hope this helps! Let us know if there are further questions.

Best regards!

**Comment by ZhengtingHuang888** [comment]
Thank you very much！
