### ISSUE TITLE
Drug repurposing task prediction files?

### ISSUE THREAD

**Issue by allaway** [emyyue/BioPathNet#3]
Hello - I was wondering if the prediction results for the drug repurposing task are available anywhere? I took a look at the supplementary data and this repository, but was unable to find them. This would be a great source of information for mining new drug predictions!

**Comment by emyyue** [comment]
Hi,

thanks a lot for your interest! We used the PrimeKG database and the [TxGNN](https://github.com/mims-harvard/TxGNN) TxData.prepare_split command to generate the splits, which were processed into the right format for BioPathNet. The whole procedure can be reproduced using [reproduce/primekg/01_get_datasplit.py](https://github.com/emyyue/BioPathNet/blob/main/reproduce/primekg/01_get_datasplit.py), e.g. `python 01_get_datasplit.py --seed 42 --split cell_proliferation --source ../data/ `.

Hope this helps. Best
